version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  AfterInstall:
    - location: deploy-scripts/application-start-hook.sh
      timeout: 60
      runas: ec2-user
