version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - cd backend
      - chmod +x gradlew
      - ./gradlew build

artifacts:
  base-directory: backend/build/libs
  files:
    - '*.jar'
