version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - cd backend
      - chmod +x gradlew
      - ./gradlew build
      - cd ..

artifacts:
  files:
    - appspec.yml
    - deploy-scripts/**/*
    - backend/build/libs/*.jar
